name: GitHub Environment Secrets Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  GitHub-Secret-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "$SSH_KEY" | base64'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.PRIVATE_KEY }}
  GitHub-Env-Secret-Actions:
    environment: Dev
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "$SSH_KEY" | base64'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.PRIVATE_KEY }}
  GitHub-No-Secret-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "$SSH_KEY" | base64'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.NOT_AVAILABLE }}
