name: Create/update tag
on:
  workflow_dispatch:
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          token: ${{ secrets.TOKEN_GITHUB }}
      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "latest"
          message: "Latest release"
          github_token: ${{ secrets.TOKEN_GITHUB }}
