name: Check Branch Exist
on:
  workflow_dispatch:
jobs:
  last-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: check_again
        shell: bash
        run: |
          if git rev-parse --verify --quiet main ; then
            echo "Working"
          else
            echo "Working NOT"
          fi
        
      - name: check
        shell: bash
        run: |
          if git rev-parse --verify --quiet mainer ; then
            echo "Working"
          else
            echo "Working NOT"
          fi
        

        
      - name: Print Status
        run: "echo ${{ steps.check.outputs.status }}"
        
      - name: Print Exist Status
        run: "echo ${{ steps.check_again.outputs.status }}"
