name: Last Run status
on:
  workflow_dispatch:
jobs:
  last-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get previous workflow status
        uses: Mercymeilya/last-workflow-status@v0.3.3
        id: last_status
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Status
        run: "echo ${{ steps.last_status.outputs.last_status }}"
