name: Synchronous Workflow
on:
  workflow_dispatch:
    inputs:
        trigger-job:
          description: 'Which job to run'
          required: true
          default: 'both'
          type: choice
          options:
          - both
          - first 
          - second
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check to exit
        if: ${{ github.event.inputs.trigger-job == 'second' }}
        run: exit 0
      - name: Print Status
        run: "echo First Job"
  second-job:
    needs: job1
    if: ${{ github.event.inputs.trigger-job == 'both' ||  github.event.inputs.trigger-job == 'second' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print Status
        run: "echo Second Job "
        
